//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ingenieriaInversa_final
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historial
    {
        public int Id { get; set; }
        public string id_Destino { get; set; }
        public string id_origen { get; set; }
        public string Resultado { get; set; }
        public string Fecha_consulta { get; set; }
    }
}
