//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ingenieriaInversa
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConversionFactores
    {
        public int id { get; set; }
        public int idMonedaOrigen { get; set; }
        public int idMonedaDestino { get; set; }
        public decimal FactorConversion { get; set; }
    
        public virtual monedas monedas { get; set; }
        public virtual monedas monedas1 { get; set; }
    }
}
