//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ingenieriaInversa
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class monedasDBEntities : DbContext
    {
        public monedasDBEntities()
            : base("name=monedasDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<monedas> monedas { get; set; }
        public virtual DbSet<ConversionFactores> ConversionFactores { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
